#!/bin/bash
echo "🔍 Diagnostic MAMP"
echo "=================="
echo ""
echo "📌 Ports MAMP :"
echo "--- Port 8889 (MySQL) ---"
lsof -i :8889 2>&1 | head -5 || echo "✅ Port libre"
echo ""
echo "--- Port 8888 (Apache) ---"
lsof -i :8888 2>&1 | head -5 || echo "✅ Port libre"
echo ""
echo "📌 Processus MySQL :"
ps aux | grep mysql | grep -v grep | head -5 || echo "✅ Aucun processus MySQL"
echo ""
echo "📌 Processus MAMP :"
ps aux | grep -i mamp | grep -v grep | head -5 || echo "✅ Aucun processus MAMP"
echo ""
echo "📌 Test connexion MySQL (si MAMP est démarré) :"
mysql -h 127.0.0.1 -P 8889 -u root -proot -e "SELECT 'MySQL OK' as status;" 2>&1 | head -3 || echo "❌ MySQL non accessible"
